---
#
# Installing Elasticsearch
#
# Adds the apt-key for Elasticsearch
- name: Add Elasticsearch apt-key
  rpm_key:
   key: "https://packages.elastic.co/GPG-KEY-elasticsearch"
   state: present
# Add the Elasticsearch APT-repository
- name: Adding Elasticsearch APT repository
  copy:
   src: elasticsearch.repo
   dest: /etc/yum.repos.d/elasticsearch.repo
   mode: 0644

# Install Elasticsearch
- name: Update repositories cache and install Elasticsearch
  yum: pkg=elasticsearch state=installed

# Update Elasticsearch config file to only allow localhost connections
- name: Updating the config file to restrict outside access
  lineinfile:
   destfile: /etc/elasticsearch/elasticsearch.yml
   regexp: 'network.host:'
   line: 'network.host: 0.0.0.0'
# Restart Elasticsearch
- name: Restarting Elasticsearch
  service:
   name: elasticsearch
   state: restarted
