# This is your main playbook you will run with:
# ansible-playbook site.yml
# You can kick off everything from this playbook.
# Or, you can create separate playbooks in this directory for specific orchestration events.

---
- hosts: all
  remote_user: ec2-user
  become: yes
  become_user: root

  roles:
    - { role: elasticsearch }
