---
#
# Installing Logstash
#
- name: Add Elasticsearch GPG key
  rpm_key:
    key: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present

- name: Adding Elasticsearch yum repository
  copy:
    src: elasticsearch.repo
    dest: /etc/yum.repos.d/elasticsearch.repo
    mode: 0644

- name: Uninstall logstash
  yum: pkg=logstash state=removed

- name: Update repositories cache and install Logstash
  yum: pkg=logstash state=installed

# Update the Logstash config files
- name: Copy footprints logstash config file
  copy:
   src: ~/ansible-automated-deploy/ansible/files/logstash-footprints.conf
   dest: /etc/logstash/conf.d/logstash-footprints.conf

- name: Updating the config file to decrease JVM min heap space
  lineinfile:
   destfile: /etc/logstash/jvm.options
   regexp: '-Xms'
   line: '-Xms512m'

- name: Updating the config file to decrease JVM max heap space
  lineinfile:
   destfile: /etc/logstash/jvm.options
   regexp: '-Xmx'
   line: '-Xmx512m'

- name: Update the config file to set REST endpoint
  lineinfile:
    destfile: /etc/logstash/logstash.yml
    regexp: 'http.host:'
    line: 'http.host: 0.0.0.0'

- name: Update the config file to set REST endpoint port
  lineinfile:
    destfile: /etc/logstash/logstash.yml
    regexp: 'http.port:'
    line: 'http.port: 9600-9700'

- name: Update the config file to set path to logstash logs
  lineinfile:
    destfile: /etc/logstash/logstash.yml
    regexp: 'path.logs:'
    line: 'path.logs: /var/log/logstash'

- name: Updating the config file to decrease JVM min heap space
  lineinfile:
   destfile: /etc/logstash/jvm.options
   regexp: '-Xms2g'
   line: '-Xms512m'

- name: Register logstash as a service
  command: initctl start logstash

- name: Restarting Logstash
  service:
   name: logstash
   state: restarted
